### ISSUE TITLE
USER STORY: Login & Signup

### ISSUE THREAD

**Issue by DarkoZlatarek** [DarkoZlatarek/online_dog_show#1]
As a **role** I can **capability** so that **received benefit**

# ACCEPTANCE CRITERIA:
* User can log in
* User can log out
* User can sign up
* Easy to navigate login/signup form

# TASKS:
- [ ] install AllAuth
- [ ] add AllAuth to settings.py
- [ ] create signup/login pages
- [ ] add URL path
