### ISSUE TITLE
USER STORY: Enter competition

### ISSUE THREAD

**Issue by DarkoZlatarek** [DarkoZlatarek/online_dog_show#2]
As a **User** I can **submit my dog photo** so that **can be in the competition**

# ACCEPTANCE CRITERIA:
* user must be able to login to the site
* user must be able to submit their photo, pending approval

# TASKS:
- [ ] Create form
- [ ] Implement class in views.py
- [ ] Link URL path
- [ ] build enter competition page
