### ISSUE TITLE
USER STORY: Like photos

### ISSUE THREAD

**Issue by DarkoZlatarek** [DarkoZlatarek/online_dog_show#4]
As a **User** I can **like photos** so that **the photo I liked gets more likes**

## ACCEPTANCE CRITERIA:
* like/unlike a photos with the click of a button

## TASKS:
- [ ] display heart as full/empty depending upon liked/unliked status
- [ ] build function in views
- [ ] build URL path
