### ISSUE TITLE
USER STORY: View competition

### ISSUE THREAD

**Issue by DarkoZlatarek** [DarkoZlatarek/online_dog_show#5]
As a **user** I can **view competition page** so that **I can see who entered the competition**

## ACCEPTANCE CRITERIA:
* a competition page that populates with the photos uploaded

## TASKS:
- [ ] build model
- [ ] create new function
- [ ] link to URLS
- [ ] create html page
