### ISSUE TITLE
USER STORY: View photos

### ISSUE THREAD

**Issue by DarkoZlatarek** [DarkoZlatarek/online_dog_show#6]
As a **user** I can **click on the photo** so that **I can see and read more about it**

## ACCEPTANCE CRITERIA:
* photo detail page for more info about the photos and the dog

## TASKS:
- [ ] create view code
- [ ] connect to urls.py
- [ ] html template to render view
