### ISSUE TITLE
USER STORY: Photo comments

### ISSUE THREAD

**Issue by DarkoZlatarek** [DarkoZlatarek/online_dog_show#7]
As a **user** I can **post comments on the photo** so that **I can tell what I think about the photo**

## ACCEPTANCE CRITERIA:
* ability to leave a comment

## TASKS:
- [ ] install cripsy forms
- [ ] create forms.py
- [ ] add form to function
- [ ] add form to competition page
